//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintingHousesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveriesPostOffices
    {
        public int C_id { get; set; }
        public int C_idPrintingNewspapers { get; set; }
        public int C_idPostOffices { get; set; }
    
        public virtual PostOffices PostOffices { get; set; }
        public virtual PrintingNewspapers PrintingNewspapers { get; set; }
    }
}
