//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintingHousesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOffices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostOffices()
        {
            this.DeliveriesPostOffices = new HashSet<DeliveriesPostOffices>();
        }
    
        public int C_id { get; set; }
        public string PostOfficeName { get; set; }
        public string PhoneNumber { get; set; }
        public string PostOfficeAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesPostOffices> DeliveriesPostOffices { get; set; }
    }
}
