//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintingHousesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintingHouses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrintingHouses()
        {
            this.PrintingNewspapers = new HashSet<PrintingNewspapers>();
        }
    
        public string PrintingHouseName { get; set; }
        public string PrintingHouseAddress { get; set; }
        public int MaxEdition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintingNewspapers> PrintingNewspapers { get; set; }
    }
}
